services:
  - type: web
    name: deentrada
    env: docker
    image: pretix/standalone:stable
    autoDeploy: true
    plan: starter
    envVars:
      - key: DATABASE_HOST
        fromDatabase:
          name: pretix-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: pretix-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: pretix-db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: pretix-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: pretix-db
          property: password
      - key: SECRET_KEY
        generateValue: true
      - key: SITE_URL
        value: https://deentrada.onrender.com
      - key: INSTANCE_NAME
        value: Sistema de Entradas
      - key: REGISTRATION
        value: "true"
      - key: DEBUG
        value: "false"
      - key: MAIL_FROM
        value: "noreply@deentrada.onrender.com"
      - key: PORT
        value: "8000"
      - key: GUNICORN_CMD_ARGS
        value: "--bind=0.0.0.0:8000 --workers=2"

databases:
  - name: pretix-db
    plan: starter
    postgresMajorVersion: 14
